// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGdXBvfJQ2ui2SVS4d3bCkXhCHAtQXqyQ',
    appId: '1:779822490887:web:09b2526203b279d0b511a2',
    messagingSenderId: '779822490887',
    projectId: 'prayer-app-e5e0f',
    authDomain: 'prayer-app-e5e0f.firebaseapp.com',
    storageBucket: 'prayer-app-e5e0f.appspot.com',
    measurementId: 'G-M96R3YM2GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKPPmleplkvIYmeNytTzxc-DaM1fu0H-o',
    appId: '1:779822490887:android:4a92af9f0a8cab68b511a2',
    messagingSenderId: '779822490887',
    projectId: 'prayer-app-e5e0f',
    storageBucket: 'prayer-app-e5e0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbuD4PeK_sPjFun0NNob0pj5anQZdkOJ4',
    appId: '1:779822490887:ios:525171bcbcda4698b511a2',
    messagingSenderId: '779822490887',
    projectId: 'prayer-app-e5e0f',
    storageBucket: 'prayer-app-e5e0f.appspot.com',
    iosClientId: '779822490887-i3epv84g9mc347hnpka26s3kbi19rs14.apps.googleusercontent.com',
    iosBundleId: 'com.example.prayertime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbuD4PeK_sPjFun0NNob0pj5anQZdkOJ4',
    appId: '1:779822490887:ios:525171bcbcda4698b511a2',
    messagingSenderId: '779822490887',
    projectId: 'prayer-app-e5e0f',
    storageBucket: 'prayer-app-e5e0f.appspot.com',
    iosClientId: '779822490887-i3epv84g9mc347hnpka26s3kbi19rs14.apps.googleusercontent.com',
    iosBundleId: 'com.example.prayertime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGdXBvfJQ2ui2SVS4d3bCkXhCHAtQXqyQ',
    appId: '1:779822490887:web:77a10048f98ff6aab511a2',
    messagingSenderId: '779822490887',
    projectId: 'prayer-app-e5e0f',
    authDomain: 'prayer-app-e5e0f.firebaseapp.com',
    storageBucket: 'prayer-app-e5e0f.appspot.com',
    measurementId: 'G-50CW175G0M',
  );
}
